#!/bin/bash

# Script para configurar variáveis de ambiente no Vercel
# Use: ./configure-vercel.sh

echo "🚀 Configurando FolhaPonto no Vercel..."
echo ""
echo "⚠️  IMPORTANTE: Configure estas variáveis de ambiente no Vercel:"
echo ""
echo "📋 Vá para: https://vercel.com/dig-ep/digepundf/settings/environment-variables"
echo ""
echo "Adicione as seguintes variáveis:"
echo ""
echo "1. SECRET_KEY"
echo "   Valor: $(openssl rand -base64 32 | head -c 64)"
echo ""
echo "2. JWT_ALGORITHM"
echo "   Valor: HS256"
echo ""
echo "3. JWT_EXPIRATION_MINUTES"
echo "   Valor: 480"
echo ""
echo "4. ADMIN_USERNAME"
echo "   Valor: admin@undf.edu.br"
echo ""
echo "5. ADMIN_PASSWORD"
echo "   Valor: (escolha uma senha segura)"
echo ""
echo "6. PONTO_DATA_DIR"
echo "   Valor: /tmp/folhaponto"
echo ""
echo "✅ Após configurar, o Vercel fará deploy automaticamente!"
echo ""
echo "📍 Seu site estará em:"
echo "   - https://digepundf.vercel.app"
echo ""
echo "🧪 Teste com:"
echo "   curl https://digepundf.vercel.app/"
