#!/bin/bash

# 🎯 ROTEIRO PASSO-A-PASSO: Conectar FolhaPonto com Vercel Novo

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                  📋 ROTEIRO CONEXÃO VERCEL NOVO                       ║"
echo "║              https://vercel.com/dig-ep/folha-ponto                    ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 STATUS ATUAL:"
echo "   ✅ Código versionado no GitHub"
echo "   ✅ Pronto para deploy no Vercel"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "🚀 AÇÕES NECESSÁRIAS:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "⏱️  PASSO 1: Abrir Vercel"
echo "   URL: https://vercel.com/dig-ep/folha-ponto"
echo "   Tempo estimado: 10 segundos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "🔗 PASSO 2: Conectar Repositório (Se Necessário)"
echo "   1. Clique em 'Settings'"
echo "   2. Vá para 'Git'"
echo "   3. Procure por 'Connected Repositories'"
echo "   4. Se não estiver conectado:"
echo "      a. Clique 'Connect Repository'"
echo "      b. Selecione: Daniel-Francisc/FolhaPonto"
echo "      c. Clique 'Connect'"
echo "   Tempo estimado: 2 minutos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "🔐 PASSO 3: Configurar Variáveis de Ambiente"
echo "   1. Em 'Settings', clique 'Environment Variables'"
echo "   2. Adicione as 6 variáveis abaixo:"
echo ""
echo "   📝 Variável 1:"
echo "      Nome: SECRET_KEY"
echo "      Valor: (escolha uma opção abaixo)"
echo ""
echo "      OPÇÃO A (copie exatamente):"
echo "      7368da5a8c13828014929219c84613d1b1aa24bc5a067ee42aaed7ffa32d76c4"
echo ""
echo "      OPÇÃO B (alternativa):"
echo "      b7d663eadc09b237d908fdb29833c83eac0de987921f2630e196e11a13662d6d"
echo ""
echo "   📝 Variável 2:"
echo "      Nome: JWT_ALGORITHM"
echo "      Valor: HS256"
echo ""
echo "   📝 Variável 3:"
echo "      Nome: JWT_EXPIRATION_MINUTES"
echo "      Valor: 480"
echo ""
echo "   📝 Variável 4:"
echo "      Nome: ADMIN_USERNAME"
echo "      Valor: admin@undf.edu.br"
echo ""
echo "   📝 Variável 5:"
echo "      Nome: ADMIN_PASSWORD"
echo "      Valor: SeNhA#12345 (escolha uma senha forte!)"
echo ""
echo "   📝 Variável 6:"
echo "      Nome: PONTO_DATA_DIR"
echo "      Valor: /tmp/folhaponto"
echo ""
echo "   Após adicionar cada uma, clique 'Save'"
echo "   Tempo estimado: 5 minutos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "🚀 PASSO 4: Fazer Deploy"
echo "   1. Volte para 'Deployments'"
echo "   2. Procure pelo último deployment (topo da lista)"
echo "   3. Clique nos 3 pontinhos (...) ao lado"
echo "   4. Escolha 'Redeploy'"
echo "   5. Confirme: 'Redeploy'"
echo ""
echo "   O sistema começará a compilar e fazer deploy"
echo "   Tempo estimado: 2-3 minutos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "⏳ PASSO 5: Aguardar Conclusão"
echo "   Você verá os status:"
echo "   🔄 Building... (compilando)"
echo "   🔄 Installing... (instalando dependências)"
echo "   ✅ Ready (pronto!)"
echo ""
echo "   Quando ficar VERDE e dizer 'Ready', está pronto!"
echo "   Tempo estimado: espera 2-3 minutos"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "🌐 PASSO 6: Acessar o Sistema"
echo "   URL: https://folha-ponto.vercel.app"
echo ""
echo "   Login:"
echo "   Email: admin@undf.edu.br"
echo "   Senha: SeNhA#12345 (ou a que você definiu)"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📋 CHECKLIST FINAL:"
echo ""
echo "   [ ] Repositório conectado no Vercel"
echo "   [ ] SECRET_KEY configurado"
echo "   [ ] JWT_ALGORITHM = HS256"
echo "   [ ] JWT_EXPIRATION_MINUTES = 480"
echo "   [ ] ADMIN_USERNAME = admin@undf.edu.br"
echo "   [ ] ADMIN_PASSWORD definido"
echo "   [ ] PONTO_DATA_DIR = /tmp/folhaponto"
echo "   [ ] Deploy clicado e em andamento"
echo "   [ ] Status do deployment: GREEN ✅"
echo "   [ ] Sistema acessível em https://folha-ponto.vercel.app"
echo "   [ ] Login realizado com sucesso"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ PRONTO! Seu FolhaPonto Digital está no ar!"
echo ""
echo "🎉 Sistema completo:"
echo "   • Dashboard com estatísticas"
echo "   • Upload de folhas de ponto"
echo "   • Conferência OCR (processamento de imagens)"
echo "   • Arquivo de folhas processadas"
echo "   • Gerenciamento de servidores"
echo "   • Fila de envios por email"
echo "   • Auditoria de todas as operações"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
